# Site settings
title: "m4jrt0m"
email: m4jrt0m@gmail.com
description: "Welcome :D"
baseurl: ""
url: ""
title_description: ""
title_image: "https://avatars.githubusercontent.com/u/72045872?s=400&u=77de714fbf57b321ef0e1ec7d25ca83b2d42b726&v=4"
github_repository: https://github.com/m4jrt0m/m4jrt0m.github.io
post_limit: 5

# Social usernames/URLs
github_username:  m4jrt0m

# Footer
footer: "&lt;/&gt; on <a href=\"https://github.com/m4jrt0m/m4jrt0m.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
